apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhdh-test
  namespace: openshift-gitops 
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./components/rhdh-test/overlays/development
    repoURL: https://github.com/jduimovich/rhdh-test-gitops
    targetRevision: main
  destination:
    namespace: rhdh-test
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
